
###############################
# Copyright (C) Anny Wang.
# Copyright (C) Hupu, Inc.
###############################

CXX=g++
CXXFLAGS=-std=c++11 -O3 -Wall -Wno-invalid-offsetof
LDFLAGS=

AR=ar rc
RANLIB=ranlib

BASEPATH=../../base
COMMPATH=../command
INCPATH=-I./$(BASEPATH) -I./$(COMMPATH)
LDPATH=

SRCPATH=./
OBJECTS=./$(BASEPATH)/wMsgQueue.o \
		./$(BASEPATH)/wMisc.o \
		./$(BASEPATH)/wSocket.o \
		./$(BASEPATH)/wTcpSocket.o \
		./$(BASEPATH)/wUnixSocket.o \
		./$(BASEPATH)/wTask.o \
		./$(BASEPATH)/wShm.o \
		./$(BASEPATH)/wSignal.o \
		\
		./$(SRCPATH)/agent_api.o

TARGET=libagent_api.a

.PHONY:all clean install

all: $(TARGET)

$(TARGET):$(OBJECTS)
	@echo "Compiling $@"
	${AR} $@ $^

%.o:%.cpp
	$(CXX) $(CXXFLAGS) $(INCPATH) -c $< -o $@

%.d:%.cpp
	@set -e; rm -f $@; $(CXX) -MM $< $(INCPATH) > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

-include $(OBJECTS:.o=.d)

clean:
	-rm -f $(BASEPATH)/*.o $(BASEPATH)/*.d $(BASEPATH)/*.d.*
	-rm -f $(TARGET) $(SRCPATH)/*.o $(SRCPATH)/*.d $(SRCPATH)/*.d.*

install:
	-mv -f $(TARGET) /usr/lib
